### ISSUE TITLE
Unable to send verification email

### ISSUE THREAD

**Issue by alimaqsood3** [msaad1999/PHP-Login-System#10]
hello sir,
    i am facing an issue when i try to send email to verify from localhost it shows this below in pic.kindly help me.i am trying from two days but noting is happning
<img width="852" alt="git" src="https://user-images.githubusercontent.com/44001150/76295331-3e8a5d00-62d6-11ea-8022-24628f1d3fe8.PNG">

**Comment by msaad1999** [comment]
Have you setup credentials for your own email account? If not, do so in the `assets/setup/env.php`. Or if you already have, the problem might be failure in authentication of the account, try looking into that.

**Comment by alimaqsood3** [comment]
thank you soo for the quick response.these are
<img width="878" alt="git2" src="https://user-images.githubusercontent.com/44001150/76298051-acd11e80-62da-11ea-807e-625de341b6a0.PNG">

**Comment by alimaqsood3** [comment]
Thank you soo much for the quick response sir.
<img width="878" alt="git2" src="https://user-images.githubusercontent.com/44001150/76298578-7e077800-62db-11ea-8dc7-9fa07183821f.PNG">
these are the credentials but noting happen

**Comment by msaad1999** [comment]
This is a very irritating problem I myself have been encountering a lot lately. This happens with Gmail accounts. I am not aware of any new changes Google might have implemented, but it's causing a lot of problems in connecting Gmail accounts with apps like these. Try these steps (not necessarily all):
- enable access to less secure apps in your Gmail account. 
- enable 2 factor authentication in your account, then generate an `app password` for any device, then use that password here in the application.
- If all else fails try using another account other than a Gmail one.

**Comment by AlbertHart** [comment]
I hope that is not an actual gmail account and password shown in the image - if so we should edit it, and blot it out.

**Comment by msaad1999** [comment]
I sincerely hope I was not wrong in assuming something similar to 'sampledpassword' or 'examplepassword' was not a genuine one, however I do agree that it is never really advisable to reveal any email address. I have hidden that comment, which is something I honestly should have done a while ago.
Sincerest apologies @alimaqsood3, hope you didn't get fake lucky draw awards.
