### ISSUE TITLE
Getting Fetal error

### ISSUE THREAD

**Issue by dhirajsah** [msaad1999/PHP-Login-System#13]
Fatal error: Call to undefined function random_bytes() in C:\wamp64\www\php-login-system\assets\includes\security_functions.php on line 30

**Comment by msaad1999** [comment]
random_bytes() was introduced in PHP 7. Best option would be to upgrade your PHP version.
Another solution would be to use a custom function in place of random_bytes(). Just make sure this is inserted at the top of the security_functions.php file, so it gets called before random_bytes()
```php
if( !function_exists('random_bytes') )
{
    function random_bytes($length = 6)
    {
        $characters = '0123456789';
        $characters_length = strlen($characters);
        $output = '';
        for ($i = 0; $i < $length; $i++)
            $output .= $characters[rand(0, $characters_length - 1)];

        return $output;
    }
}
```
