### ISSUE TITLE
Notice: Undefined offset: 1 in C:\xampp\htdocs\PHP-Login-System-master\assets\includes\auth_functions.php on line 133

### ISSUE THREAD

**Issue by MusheAbdulHakim** [msaad1999/PHP-Login-System#16]
Any idea why and how do i fix it

**Comment by msaad1999** [comment]
> Sorry for the delayed response.

The line being mentioned by the error message doesn't seem to show any issues in implementation, and I have not been able to get this error on testing either. It might be a bit more helpful if you show where and how you got this error, and whether you made any changes to the code anywhere.

**Comment by msaad1999** [comment]
closing due to no response
