### ISSUE TITLE
phpmailer shows  "email could not be sent, try again later"

### ISSUE THREAD

**Issue by john2715** [msaad1999/PHP-Login-System#20]
bro i need a help im a student now im using ur login register code.
 now register, login code works perfectly but mail doesn't send ("email could not be sent, try again later" )
how to solve this problem

**Comment by msaad1999** [comment]
I would recommend looking at this closed issue:
> https://github.com/msaad1999/PHP-Login-System/issues/10

This concerns the same problems with sending emails and the proper setup for configuring them
