### ISSUE TITLE
Do you consider to develop a new version with PDO instead of mysqli?

### ISSUE THREAD

**Issue by meo1** [msaad1999/PHP-Login-System#28]
Very nice script. I appreciate  a lot. Thank you. But do you consider to develop a new version with PDO instead of mysqli?

**Comment by msaad1999** [comment]
I did initially intend to phase over to PDO, but unfortunately I am having a lot of trouble in further working on this project due to several commitments. It is most likely I may not replace mysqli with PDO anytime soon. Apologies for that.
