### ISSUE TITLE
Problem with Contact Form

### ISSUE THREAD

**Issue by ectic2020** [msaad1999/PHP-Login-System#29]
Hello @msaad1999,
Thank you for the PHP-Login-System which is a great pleasure for me
I follow the contact form which does not work 'When I am connected and even offline nothing happens'

**Comment by msaad1999** [comment]
Can you provide more details on what exactly does not work or if there is any error, in which case what is the error stack trace.

**Comment by Noajuan** [comment]
Hi, thanks for your help, i'm a student of cibersecurity, this project just is for learn, and apply my abilities, i'm sure that project have many problems and errors, now i don't work in that project, but i will try to check again and tell you more details. Em 27 de mar de 2021 00:34, Muhammad Saad ***@***.***> escreveu:
Can you provide more details on what exactly does not work or if there is any error, in which case what is the error stack trace.

**Comment by ectic2020** [comment]
@msaad1999 
When I fill in the information and I submit it nothing does not get an error message, even if I am connected or not.

**Comment by msaad1999** [comment]
Try opening your inspect element in the browser and look at the network tab and console while submitting the form. If something is going wrong it should definitely be visible in one or both of those places.

**Comment by ectic2020** [comment]
@msaad1999 
this is the only message I could see
HTTP error: status code 300, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by msaad1999** [comment]
This worked for me, do tell if it doesn't fix your issue

- In your browser window, go to inspect -> settings -> preferences -> Sources 
- Uncheck `enable javascript source maps` and `enable css source map`.
- Refresh.

**Comment by ectic2020** [comment]
Salut @msaad1999 
I tried nothing works
![123000](https://user-images.githubusercontent.com/70666622/113871097-75b59100-97aa-11eb-9f1e-28d89a11ae81.JPG)

**Comment by msaad1999** [comment]
will look into this more

**Comment by ectic2020** [comment]
I'm just starting out in programming, it's not really easy for me.
If there is a way to help me, that is fine.
Thank you.

**Comment by ectic2020** [comment]
Hi @msaad1999 
on this project do you use a small form to insert the data into the database and generate a 6-digit code and photo

**Comment by Coliwob** [comment]
Did this error get resolved? I have a similar problem.

**Comment by Coliwob** [comment]
Found the problem. @ectic2020 how did you get on? Did you manage to resolve?
